version: 2

jobs:

  build:
    working_directory: ~/wdi

    docker:
      - image: circleci/python:3.6.1

      - image: circleci/postgres:9.6.3

    environment:
      - PROJECT_DIR: "~/wdi/tpot-warehouse"

      - VENV_NAME:  "tpot-wh"

      - VENV_DIR: "~/tpot-wh"

    steps:
      - checkout:

      - run:
          name: activate-venv
          command: |
              python3 -m venv "${VENV_NAME}"
              cd "${VENV_DIR}"
              . tpot-wh/bin/activate "${VENV_NAME}"
              working_directory: ~
      - run:
          name: pip-install
          command: pip install -U requirements.dev.txt
          working_directory: ~/wdi/tpot-warehouse

      - run:
          name: update-db-config
          command: mv conf/db.dev.yml conf/db.yml
          working_directory: ~/wdi/tpot-warehouse

      - run:
          name: test-transactional
          command: pytest -v --name transactional tests/test_dbtransactional.py
          working_directory: ~/wdi/tpot-warehouse