version: 2

jobs:

  build:
    working_directory: ~/wdi

    docker:
      - image: circleci/python:3.6.1

      - image: circleci/postgres:9.6.3

    environment:
      - PROJECT_DIR: "~/wdi/tpot-warehouse"

      - VENV_NAME:  "tpot-wh"

      - VENV_DIR: "~/tpot-wh"

    steps:
      - checkout

      - run:
          name: Activate python virtual environment
          working_directory: ~
          command: |
              python3 -m venv "${VENV_NAME}"
              cd "${VENV_DIR}"
              . tpot-wh/bin/activate "${VENV_NAME}"

      - run:
          name: Install required python modules
          working_directory: ~/wdi/tpot-warehouse
          command: pip install -U requirements.dev.txt

      - run:
          working_directory: ~/wdi/tpot-warehouse
          name: Update database connection parameters
          command: mv conf/db.dev.yml conf/db.yml

      - run:
          name: Run transactional database application tests
          command: pytest -v --name transactional tests/test_dbtransactional.py
          working_directory: ~/wdi/tpot-warehouse