version: 2

jobs:

  build:
    working_directory: ~/wdi

    docker:
      - image: circleci/python:3.6.1

      - image: circleci/postgres:9.6.3

    environment:
      - VENV_NAME:  "tpot-wh"

      - VENV_DIR: "~/pyenv/tpot-wh"

    steps:
      - run:
          name: Create working directories
          pwd: ~
          command: |
            rm -rfv ~/pyenv && mkdir -pv ~/pyenv
            rm -rfv ~/wdi && mkdir -pv ~/wdi

      - checkout

      - run:
          name: Activate python virtual environment
          pwd: ~/pyenv
          command: |
              python3 -m venv "${VENV_NAME}"
              . tpot-wh/bin/activate

      - run:
          name: Install required python modules
          pwd: ~/wdi/tpot-warehouse
          command: echo $(pwd) && pip install -r requirements.dev.txt

      - run:
          name: Update database connection parameters
          pwd: ~/wdi/tpot-warehouse
          command: mv -v conf/db.dev.yml conf/db.yml

      - run:
          name: Run transactional database application tests
          pwd: ~/wdi/tpot-warehouse
          command: pytest -v --name transactional tests/test_dbtransactional.py